### ISSUE TITLE
Cannot take off?

### ISSUE THREAD

**Issue by BrewMyTea** [juniper-mods/lethal-company-compass-mod#1]
Bug tested with a few other mods. 

Seems this one is isolated to a bug when attempting to take off the ship never lands, causing inability to save losing all progress. 

Very strange.

**Comment by juniper-mods** [comment]
hey brew, thats super weird. ill take a look

**Comment by BrewMyTea** [comment]
> hey brew, thats super weird. ill take a look

Sorry mate, I was mistaken. I think it was actually a problem or conflict with the BiggerLobbies mod rather than your mod. 

I ended up having this bug reoccur without your Compass mod installed, the only consistency was BiggerLobbies.

**Comment by juniper-mods** [comment]
ah okay, glad for that :)
